<?php
   /**
   * Implements hook_menu().
   */
   function review_menu() {


      $items['reviews'] = array(
         'title'            => 'Reviews',
         'page callback'    => 'reviews_listing_page',
         'access arguments' => array('access content'),
      );
   }

   /**
   * Implements hook_block_info().
   */
   function review_block_info() {
      $blocks = array();

      $blocks['reviews'] = array(
         'info' => 'Reviews',
         'cache' => DRUPAL_NO_CACHE
      );

      return $blocks;
   }

   /**
   * Implements hook_block_view().
   */
   function review_block_view($delta = '') {
      $block = array();
      if($delta == 'reviews'){
         $block['subject'] = '';
         $block['content'] = array(
            '#theme' => 'review_slideshow',
            '#reviews' => review_get_slideshow_format(),
         );
      }

      return $block;
   }

   /**
   * Implements hook_block_configure().
   */
   function review_block_configure($delta = '') {
      /**



      */
   }

   /**
   * Implements hook_theme().
   */
   function review_theme($existing, $type, $theme, $path) {
      return array(
         'review_slideshow'       => array(
            'template' => 'templates/review-slideshow',
            'variables' => array(
               'reviews' => array(),
            ),
         ),
      );
   }


   function review_get_reviews($limit = null) {
      static $nodes = array();

      if (!empty($nodes)) {
         return $nodes;
      }

      $query = db_select('node', 'n')
      ->fields('n', array('nid'))
      ->condition('status', 1)
      ->condition('type', 'review')
      ->orderRandom();

      if ($limit != null)
         $query->range(null,$limit);

      $result = $query->execute();

      $nids = array();
      foreach ($result as $row) {
         $nids[] = $row->nid;
      }

      $nodes = node_load_multiple($nids);

      return $nodes;
   }


   function review_get_slideshow_format() {

      $nodes = review_get_reviews(3);

      foreach($nodes as $node) {
         $reviews[] = node_view($node,'full');
      }
      return $reviews;


   }
